package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

var primitiveTypes = map[string]string{
	"string":  "string",
	"int":     "number",
	"int64":   "number",
	"float64": "number",
	"bool":    "boolean",
	"any":     "any",
}

// internalTypes are server-only structs that must not be exported to the SPA.
var internalTypes = map[string]bool{
	"DashboardData":    true,
	"UserSubscription": true,
}

var syncTargets = []string{
	"internal/models/external",
	"internal/models/dashboard.go",
	"internal/models/subscription.go",
	"internal/models/privileges.go",
}

func main() {
	outputFile := "../frontend/src/lib/types.ts"

	var sb strings.Builder
	sb.WriteString("// Code generated by sync_types.go; DO NOT EDIT.\n\n")

	seen := make(map[string]bool)

	sb.WriteString("export type APIError = {\n  code: string;\n  message: string;\n};\n\n")
	seen["APIError"] = true

	for _, target := range syncTargets {
		info, err := os.Stat(target)
		if err != nil {
			fmt.Printf("Warning: target %s not found\n", target)
			continue
		}

		if info.IsDir() {
			filepath.Walk(target, func(path string, info os.FileInfo, err error) error {
				if err != nil || info.IsDir() {
					return nil
				}
				if strings.HasSuffix(path, ".go") && !strings.Contains(path, "_test") {
					parseFile(path, &sb, seen)
				}
				return nil
			})
		} else {
			parseFile(target, &sb, seen)
		}
	}

	if err := os.WriteFile(outputFile, []byte(sb.String()), 0644); err != nil {
		fmt.Printf("Error writing output file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Successfully generated types in %s\n", outputFile)
}

func parseFile(path string, sb *strings.Builder, seen map[string]bool) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		fmt.Printf("Error parsing %s: %v\n", path, err)
		return
	}

	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			typeName := typeSpec.Name.Name
			if internalTypes[typeName] || seen[typeName] {
				continue
			}

			switch t := typeSpec.Type.(type) {
			case *ast.StructType:
				writeStructType(sb, typeName, t, seen)
			case *ast.MapType:
				writeMapAlias(sb, typeName, t, seen)
			}
		}
	}
}

func writeStructType(sb *strings.Builder, typeName string, structType *ast.StructType, seen map[string]bool) {
	seen[typeName] = true
	sb.WriteString(fmt.Sprintf("export type %s = {\n", typeName))

	for _, field := range structType.Fields.List {
		jsonTag := parseJSONTag(field.Tag)
		if jsonTag == "-" {
			continue
		}

		name := fieldName(field, jsonTag)
		if name == "" {
			continue
		}

		optional := ""
		if jsonTag != "" && strings.Contains(jsonTag, "omitempty") {
			optional = "?"
		}

		sb.WriteString(fmt.Sprintf("  %s%s: %s;\n", name, optional, tsType(field.Type)))
	}

	sb.WriteString("};\n\n")
}

func writeMapAlias(sb *strings.Builder, typeName string, mapType *ast.MapType, seen map[string]bool) {
	seen[typeName] = true
	sb.WriteString(fmt.Sprintf(
		"export type %s = Record<%s, %s>;\n\n",
		typeName,
		tsType(mapType.Key),
		tsType(mapType.Value),
	))
}

func fieldName(field *ast.Field, jsonTag string) string {
	if jsonTag != "" {
		return strings.Split(jsonTag, ",")[0]
	}
	if len(field.Names) == 0 {
		return ""
	}
	return field.Names[0].Name
}

func parseJSONTag(tag *ast.BasicLit) string {
	if tag == nil {
		return ""
	}
	value := strings.Trim(tag.Value, "`")
	if !strings.Contains(value, "json:\"") {
		return ""
	}
	parts := strings.Split(value, "json:\"")
	if len(parts) < 2 {
		return ""
	}
	return strings.Split(parts[1], "\"")[0]
}

func tsType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		if mapped, ok := primitiveTypes[t.Name]; ok {
			return mapped
		}
		return t.Name
	case *ast.ArrayType:
		return tsType(t.Elt) + "[]"
	case *ast.StarExpr:
		return tsType(t.X)
	case *ast.MapType:
		return fmt.Sprintf("Record<%s, %s>", tsType(t.Key), tsType(t.Value))
	case *ast.SelectorExpr:
		if t.Sel.Name == "Time" {
			return "number"
		}
		return t.Sel.Name
	default:
		return "any"
	}
}
