package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

var typeMapping = map[string]string{
	"string":  "string",
	"int":     "number",
	"int64":   "number",
	"float64": "number",
	"bool":    "boolean",
	"any":     "any",
}

func main() {
	outputFile := "../frontend/src/lib/types.ts"
	
	targets := []string{
		"internal/models",
		"internal/models/external",
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by sync_types.go; DO NOT EDIT.\n\n")
	
	// Track seen types to avoid duplicates
	seen := make(map[string]bool)

	// Add custom types that aren't easily parsed from structs
	sb.WriteString("export type APIError = {\n  code: string;\n  message: string;\n};\n\n")
	seen["APIError"] = true
	sb.WriteString("export type ActionResult<T = unknown> = {\n  data?: T;\n  error?: string;\n  errorCode?: string;\n};\n\n")
	seen["ActionResult"] = true

	for _, target := range targets {
		info, err := os.Stat(target)
		if err != nil {
			fmt.Printf("Warning: target %s not found\n", target)
			continue
		}

		if info.IsDir() {
			filepath.Walk(target, func(path string, info os.FileInfo, err error) error {
				if !info.IsDir() && strings.HasSuffix(path, ".go") && !strings.Contains(path, "_test") {
					parseFile(path, &sb, seen)
				}
				return nil
			})
		} else {
			parseFile(target, &sb, seen)
		}
	}

	err := os.WriteFile(outputFile, []byte(sb.String()), 0644)
	if err != nil {
		fmt.Printf("Error writing output file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Successfully generated types in %s\n", outputFile)
}

func parseFile(path string, sb *strings.Builder, seen map[string]bool) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		fmt.Printf("Error parsing %s: %v\n", path, err)
		return
	}

	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			typeName := typeSpec.Name.Name
			if typeName == "UserProfile" {
				typeName = "User"
			}
			
			if seen[typeName] {
				continue
			}
			seen[typeName] = true

			sb.WriteString(fmt.Sprintf("export type %s = {\n", typeName))
// ... (rest of function unchanged)

			for _, field := range structType.Fields.List {
				jsonTag := ""
				if field.Tag != nil {
					tag := strings.Trim(field.Tag.Value, "`")
					if strings.Contains(tag, "json:\"") {
						parts := strings.Split(tag, "json:\"")
						if len(parts) > 1 {
							jsonTag = strings.Split(parts[1], "\"")[0]
						}
					}
				}

				if jsonTag == "-" {
					continue
				}

				name := ""
				if len(field.Names) > 0 {
					name = field.Names[0].Name
				}

				if jsonTag != "" {
					name = strings.Split(jsonTag, ",")[0]
				}
				
				if name == "" {
					continue
				}

				tsType := "any"
				optional := ""
				if jsonTag != "" && strings.Contains(jsonTag, "omitempty") {
					optional = "?"
				}

				tsType = getTSType(field.Type)

				sb.WriteString(fmt.Sprintf("  %s%s: %s;\n", name, optional, tsType))
			}
			sb.WriteString("};\n\n")
		}
	}
}

func getTSType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		if mapped, ok := typeMapping[t.Name]; ok {
			return mapped
		}
		if t.Name == "UserProfile" {
			return "User"
		}
		return t.Name
	case *ast.ArrayType:
		return getTSType(t.Elt) + "[]"
	case *ast.StarExpr:
		return getTSType(t.X)
	case *ast.SelectorExpr:
		// Handle things like time.Time as number (unix)
		if t.Sel.Name == "Time" {
			return "number"
		}
		return t.Sel.Name
	default:
		return "any"
	}
}
