// Code generated by sync_types.go; DO NOT EDIT.

export type APIError = {
  code: string;
  message: string;
};

export type ActionResult<T = unknown> = {
  data?: T;
  error?: string;
  errorCode?: string;
};

export type Category = {
  id: number;
  user_id: number;
  name: string;
  created_at: number;
};

export type Tag = {
  id: number;
  category_id: number;
  name: string;
  color: string;
  created_at: number;
};

export type TagFilter = {
  id: number;
  user_id: number;
  tag_id: number;
  pattern: string;
  filter_type: string;
  created_at: number;
};

export type CategoryWithTags = {
  Tags: Tag[];
};

export type TagBreakdown = {
  tag_id: number;
  tag_name: string;
  color: string;
  total: number;
};

export type DashboardWidget = {
  id: string;
  visible: boolean;
  order: number;
};

export type DashboardLayout = {
  desktop: DashboardWidget[];
  mobile: DashboardWidget[];
};

export type MonthlySpend = {
  month: string;
  total: number;
};

export type MonthCashflow = {
  spend: number;
  income: number;
};

export type DashboardSummary = {
  net_worth: number;
  cash: number;
  savings: number;
  credit_debt: number;
  loan_debt: number;
  loan_monthly_payments: number;
  investments: number;
  account_count: number;
  avg_monthly_spend: number;
  months_to_zero: number;
};

export type DashboardData = {
  summary: DashboardSummary;
  groups: any;
  transactions: Transaction[];
  spending_trend: MonthlySpend[];
  month_cashflow: MonthCashflow;
  spending_by_tag: TagBreakdown[];
  income_by_tag: TagBreakdown[];
  layout: DashboardLayout;
  edit_mode: boolean;
};

export type PlaidAccountView = {
  plaid_account_id: string;
  name: string;
  mask: string;
  subtype: string;
  balance: number;
  currency: string;
  status: string;
  is_hidden: boolean;
};

export type PlaidConnectionView = {
  row_id: string;
  institution_name: string;
  status: string;
  created_at: number;
  last_synced: number;
  accounts: PlaidAccountView[];
};

export type PlaidConnectionsPayload = {
  connections: PlaidConnectionView[];
};

export type PlaidLinkTokenResponse = {
  link_token: string;
};

export type PlaidExchangeRequest = {
  public_token: string;
};

export type LoginRequest = {
  email: string;
  password: string;
  remember: boolean;
};

export type RegisterRequest = {
  first_name: string;
  last_name: string;
  email: string;
  password: string;
  confirm_password: string;
};

export type ForgotPasswordRequest = {
  email: string;
};

export type SaveDashboardLayoutRequest = {
  device_type: string;
  widgets: DashboardWidget[];
};

export type BulkTagRequest = {
  transaction_ids: string[];
  tag_id: number;
};

export type TagFilterInput = {
  pattern: string;
  filter_type: string;
};

export type CreateTagRequest = {
  category_id: number;
  name: string;
  color: string;
  filters: TagFilterInput[];
  apply: boolean;
};

export type UpdateTagRequest = {
  name: string;
  color: string;
  category_id: number;
  filters: TagFilterInput[];
  apply: boolean;
};

export type MoveTagRequest = {
  category_id: number;
};

export type CreateCategoryRequest = {
  name: string;
};

export type UpdateCategoryRequest = {
  name: string;
};

export type DeleteCategoryRequest = {
  action: string;
  target_category_id?: number;
};

export type SessionProfile = {
  first_name: string;
  last_name: string;
  email: string;
  theme_preference: string;
};

export type DashboardAccountView = {
  name: string;
  mask: string;
  subtype: string;
  balance: number;
  monthly_payment?: number;
  status: string;
  is_hidden: boolean;
};

export type DashboardTagView = {
  name: string;
  color: string;
};

export type DashboardTransactionView = {
  date: number;
  amount: number;
  name: string;
  merchant_name: string;
  pending: boolean;
  tags?: DashboardTagView[];
};

export type TagSliceView = {
  tag_name: string;
  color: string;
  total: number;
};

export type DashboardPayload = {
  summary: DashboardSummary;
  groups: any;
  transactions: DashboardTransactionView[];
  spending_trend: MonthlySpend[];
  month_cashflow: MonthCashflow;
  spending_by_tag: TagSliceView[];
  income_by_tag: TagSliceView[];
  layout: DashboardLayout;
  edit_mode: boolean;
};

export type TransactionTagView = {
  id: number;
  name: string;
  color: string;
};

export type TransactionView = {
  id: number;
  date: number;
  amount: number;
  name: string;
  merchant_name: string;
  pending: boolean;
  tags?: TransactionTagView[];
};

export type TransactionCategoryView = {
  id: number;
  name: string;
};

export type TransactionTagOption = {
  id: number;
  name: string;
  color: string;
  category_id: number;
};

export type TransactionListPayload = {
  transactions: TransactionView[];
  total_count: number;
  page: number;
  page_size: number;
  total_pages: number;
  tags: TransactionTagOption[];
  categories: TransactionCategoryView[];
};

export type TagView = {
  id: number;
  category_id: number;
  name: string;
  color: string;
};

export type CategoryWithTagsView = {
  id: number;
  name: string;
  tags: TagView[];
};

export type TagsPayload = {
  categories: CategoryWithTagsView[];
};

export type TagFilterView = {
  pattern: string;
  filter_type: string;
};

export type SettingsProfile = {
  first_name: string;
  last_name: string;
  email: string;
  theme_preference: string;
  has_password: boolean;
  sso_providers: string[];
};

export type UpdateProfileRequest = {
  first_name: string;
  last_name: string;
};

export type UpdatePasswordRequest = {
  current_password: string;
  new_password: string;
  confirm_password: string;
};

export type UpdateThemeRequest = {
  theme: string;
};

export type DeleteAccountVerifyRequest = {
  email: string;
  password: string;
};

export type DeleteAccountReauthStatusResponse = {
  reauth_verified: boolean;
};

export type Notification = {
  message: string;
  type: string;
};

export type PageData = {
  user: User;
  title: string;
  data: any;
  reauth_success: boolean;
  notifications?: Notification[];
};

export type Account = {
  id: number;
  user_id: number;
  plaid_account_id: string;
  plaid_item_id: string;
  name: string;
  mask: string;
  type: string;
  subtype: string;
  balance: number;
  available_balance: number;
  currency: string;
  status: string;
  is_hidden: boolean;
  monthly_payment: number;
  created_at: number;
};

export type PlaidItem = {
  id: number;
  row_id: string;
  user_id: number;
  plaid_item_id: string;
  institution_id: string;
  institution_name: string;
  sync_cursor: string;
  status: string;
  error_code?: string;
  last_synced: number;
  created_at: number;
};

export type PlaidItemWithAccounts = {
  Accounts: Account[];
};

export type Session = {
  id: string;
  user_id: number;
  expires_at: number;
  reauthenticated_at: number;
  created_at: number;
};

export type Transaction = {
  id: number;
  plaid_id: number;
  plaid_transaction_id: string;
  date: number;
  amount: number;
  name: string;
  merchant_name: string;
  plaid_category: string;
  pending: boolean;
  created_at: number;
  tags?: Tag[];
};

export type TransactionFilters = {
  Search: string;
  MinAmount: number;
  MaxAmount: number;
  StartDate: number;
  EndDate: number;
  CategoryID: number;
  Tags: number[];
  SortBy: string;
  SortDir: string;
  Limit: number;
  Offset: number;
};

export type TransactionPageData = {
  Transactions: Transaction[];
  TotalCount: number;
  CurrentPage: number;
  PageSize: number;
  Filters: TransactionFilters;
  AllTags: Tag[];
  Categories: Category[];
};

export type User = {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  theme_preference: string;
  created_at: number;
  sso_logins?: UserSSO[];
};

export type UserSSO = {
  id: number;
  user_id: number;
  provider: string;
  sso_id: string;
  created_at: number;
};

