// Code generated by sync_types.go; DO NOT EDIT.

export type APIError = {
  code: string;
  message: string;
};

export type ConnectionAccountView = {
  account_id: string;
  name: string;
  mask: string;
  subtype: string;
  balance: number;
  currency: string;
  status: string;
  is_hidden: boolean;
};

export type ConnectionView = {
  row_id: string;
  institution_name: string;
  status: string;
  created_at: number;
  last_synced: number;
  accounts: ConnectionAccountView[];
};

export type ConnectionsPayload = {
  provider: string;
  connections: ConnectionView[];
  usage: PlaidUsage;
};

export type ProviderInfoResponse = {
  provider: string;
  publishable_key?: string;
};

export type CreateSessionResponse = {
  link_token?: string;
  client_secret?: string;
};

export type CompleteConnectionRequest = {
  public_token?: string;
  session_id?: string;
};

export type LoginRequest = {
  email: string;
  password: string;
  remember: boolean;
};

export type RegisterRequest = {
  first_name: string;
  last_name: string;
  email: string;
  password: string;
  confirm_password: string;
};

export type ForgotPasswordRequest = {
  email: string;
};

export type VerifyResetCodeRequest = {
  email: string;
  code: string;
};

export type ResetPasswordRequest = {
  email: string;
  code: string;
  new_password: string;
  confirm_password: string;
};

export type SaveDashboardLayoutRequest = {
  device_type: string;
  widgets: DashboardWidget[];
};

export type BulkTagRequest = {
  transaction_ids: string[];
  tag_id: number;
};

export type TagFilterInput = {
  pattern: string;
  filter_type: string;
};

export type CreateTagRequest = {
  category_id: number;
  name: string;
  color: string;
  filters: TagFilterInput[];
  apply: boolean;
};

export type UpdateTagRequest = {
  name: string;
  color: string;
  category_id: number;
  filters: TagFilterInput[];
  apply: boolean;
};

export type MoveTagRequest = {
  category_id: number;
};

export type CreateCategoryRequest = {
  name: string;
};

export type UpdateCategoryRequest = {
  name: string;
};

export type DeleteCategoryRequest = {
  action: string;
  target_category_id?: number;
};

export type ForgotPasswordResponse = {
  message: string;
  code_expires_in_seconds: number;
};

export type VerifyResetCodeResponse = {
  expires_at: number;
};

export type SessionProfile = {
  first_name: string;
  last_name: string;
  email: string;
  theme_preference: string;
  onboarding_completed: boolean;
};

export type DashboardAccountView = {
  name: string;
  mask: string;
  subtype: string;
  balance: number;
  monthly_payment?: number;
  status: string;
  is_hidden: boolean;
};

export type DashboardTagView = {
  name: string;
  color: string;
};

export type DashboardTransactionView = {
  date: number;
  amount: number;
  name: string;
  merchant_name: string;
  pending: boolean;
  tags?: DashboardTagView[];
};

export type TagSliceView = {
  tag_name: string;
  color: string;
  total: number;
};

export type DashboardAccountGroups = Record<string, DashboardAccountView[]>;

export type DashboardPayload = {
  summary: DashboardSummary;
  groups: DashboardAccountGroups;
  transactions: DashboardTransactionView[];
  spending_trend: MonthlySpend[];
  month_cashflow: MonthCashflow;
  spending_by_tag: TagSliceView[];
  income_by_tag: TagSliceView[];
  layout: DashboardLayout;
  edit_mode: boolean;
};

export type TransactionTagView = {
  id: number;
  name: string;
  color: string;
};

export type TransactionView = {
  id: number;
  date: number;
  amount: number;
  name: string;
  merchant_name: string;
  pending: boolean;
  tags?: TransactionTagView[];
};

export type TransactionCategoryView = {
  id: number;
  name: string;
};

export type TransactionTagOption = {
  id: number;
  name: string;
  color: string;
  category_id: number;
};

export type TransactionListPayload = {
  transactions: TransactionView[];
  total_count: number;
  page: number;
  page_size: number;
  total_pages: number;
  tags: TransactionTagOption[];
  categories: TransactionCategoryView[];
};

export type TagView = {
  id: number;
  category_id: number;
  name: string;
  color: string;
};

export type CategoryWithTagsView = {
  id: number;
  name: string;
  tags: TagView[];
};

export type TagsPayload = {
  categories: CategoryWithTagsView[];
};

export type TagFilterView = {
  pattern: string;
  filter_type: string;
};

export type SettingsProfile = {
  first_name: string;
  last_name: string;
  email: string;
  theme_preference: string;
  has_password: boolean;
  sso_providers: string[];
};

export type UpdateProfileRequest = {
  first_name: string;
  last_name: string;
};

export type UpdatePasswordRequest = {
  current_password: string;
  new_password: string;
  confirm_password: string;
};

export type UpdateThemeRequest = {
  theme: string;
};

export type DeleteAccountVerifyRequest = {
  email: string;
  password: string;
};

export type DeleteAccountReauthStatusResponse = {
  reauth_verified: boolean;
};

export type SubscriptionPayload = {
  tier: string;
  billing: BillingPeriod;
  limits: PlaidLimits;
  plans: TierPlan[];
  stripe_configured: boolean;
  billing_enabled: boolean;
  subscriptions_enabled: boolean;
  has_active_subscription: boolean;
  can_change_plan: boolean;
  privileges: SubscriptionPrivileges;
};

export type CheckoutSessionRequest = {
  tier: string;
};

export type CheckoutSessionResponse = {
  url: string;
};

export type BillingPortalResponse = {
  url: string;
};

export type ChangeSubscriptionRequest = {
  tier: string;
};

export type ChangeSubscriptionResponse = {
  subscription: SubscriptionPayload;
};

export type DashboardWidget = {
  id: string;
  visible: boolean;
  order: number;
};

export type DashboardLayout = {
  desktop: DashboardWidget[];
  mobile: DashboardWidget[];
};

export type MonthlySpend = {
  month: string;
  total: number;
};

export type MonthCashflow = {
  spend: number;
  income: number;
};

export type DashboardSummary = {
  net_worth: number;
  cash: number;
  savings: number;
  credit_debt: number;
  loan_debt: number;
  loan_monthly_payments: number;
  investments: number;
  account_count: number;
  avg_monthly_spend: number;
  months_to_zero: number;
};

export type PlaidLimits = {
  max_items: number;
  max_api_calls_month: number;
};

export type PlaidUsage = {
  subscription_tier: string;
  limits: PlaidLimits;
  active_items: number;
  api_calls_used: number;
  period_start: number;
  period_end: number;
};

export type BillingPeriod = {
  anchor: number;
  period_start: number;
  period_end: number;
};

export type TierPlan = {
  id: string;
  name: string;
  limits: PlaidLimits;
  price_monthly_cents: number;
};

export type UserPrivileges = {
  user_id: number;
  unlimited_limits: boolean;
  stripe_coupon_id?: string;
  notes?: string;
};

export type SubscriptionPrivileges = {
  unlimited_limits: boolean;
  has_discount: boolean;
};

